name: Make Drag And Drop Package

on:
  push:
    tags:
      - "dmg-v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Building preparation
        run: sudo apt install cmake g++
          
      - name: Build Solver App with Debian Generator
        run: ./scripts/dragndropPackage.sh      

      - name: Github Actions Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
